/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Process Information
 #	author : miyako
 #	2013/11/02
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"

#if VERSIONWIN
#include <windows.h>
#include <shellapi.h>
#endif

void CommandDispatcherInMainProcess (int32_t pProcNum, PA_PluginParameters params);

// --- Process Information (10.0)
void PROCESS_GET_ARGUMENTS(sLONG_PTR *pResult, PackagePtr pParams);
void PROCESS_Get_name(sLONG_PTR *pResult, PackagePtr pParams);
void PROCESS_Get_identifier(sLONG_PTR *pResult, PackagePtr pParams);
void PROCESS_SET_NAME(sLONG_PTR *pResult, PackagePtr pParams);
void PROCESS_Get_GUID(sLONG_PTR *pResult, PackagePtr pParams);
void PROCESS_LOG(sLONG_PTR *pResult, PackagePtr pParams);

// --- App Nap (10.9)
void END_IMPORTANT_ACTIVITY(PA_PluginParameters params);
void BEGIN_IMPORTANT_ACTIVITY(PA_PluginParameters params);

// --- System Information (10.5)
void SYSTEM_Get_cores(sLONG_PTR *pResult, PackagePtr pParams);
void SYSTEM_Get_cores_active(sLONG_PTR *pResult, PackagePtr pParams);

// --- System Information (10.6)
void SYSTEM_Get_uptime(sLONG_PTR *pResult, PackagePtr pParams);

// --- System Information (10.0)
void SYSTEM_Get_version(sLONG_PTR *pResult, PackagePtr pParams);
void SYSTEM_Get_computer_name(sLONG_PTR *pResult, PackagePtr pParams);
void SYSTEM_Get_name(sLONG_PTR *pResult, PackagePtr pParams);

#ifndef NSFoundationVersionNumber10_4
#define NSFoundationVersionNumber10_4	567.00
#endif

#ifndef NSFoundationVersionNumber10_5
#define NSFoundationVersionNumber10_5	677.00
#endif

#ifndef NSFoundationVersionNumber10_6
#define NSFoundationVersionNumber10_6 751.00
#endif

#ifndef NSFoundationVersionNumber10_7
#define NSFoundationVersionNumber10_7 833.10
#endif

#ifndef NSFoundationVersionNumber10_8
#define NSFoundationVersionNumber10_8 945.00
#endif